Adição de arquivos
Top-Alg-Wiki/Top.Alg.Wiki pull request #13
Opened 2024-10-28 19:30 UTC by renatarmd

Adicionei os arquivos homotopia-teorema-da-bola-cabeluda.tex e homotopia-identidade-e-antipoda.tex (lema para o Teorema da Bola Cabeluda). Além disso, coloquei o input deles no arquivo homotopia.tex e corrigi a referência ao Teorema da Bola Cabeluda nas consequências do homotopia-def.tex.

2024-11-08 21:34 UTC, Bybianca628 commented on conteudo/homotopia-identidade-e-antipoda.tex
> +    De fato, $H$ está bem definida pois, utilizando o fato de que $\langle x, v(x) \rangle =0$, temos $|cos(\pi t)x+sen(\pi t)\frac{v(x)}{||v(x)||}|^2=\langle cos(\pi t)x+sen(\pi t)\frac{v(x)}{||v(x)
É uma boa prática separar equações mto grande em sua própria linha usando \[\] ou $$$$. Porém acho uqe essa sequencia de igualdades ficaria melhor usando o ambiente align* (https://www.overleaf.com/learn/latex/Aligning_equations_with_amsmath)

2024-11-11 13:22 UTC, Bybianca628 commented on conteudo/homotopia-teorema-da-bola-cabeluda.tex
> +    De fato, a função é contínua, $\langle(-x_2,~x_1,~...,~-x_{2k},~x_{2k-1}), (x_1,~x_2,~...,~x_{2k-1},~x_{2k}) \rangle =-x_1x_2+x_1x_2-...-x_{2k-1}x_{2k}+x_{2k-1}x_{2k}=0$ e $v(x)\ne 0$ para todo $
separar equações grandes em sua própria linha

2024-11-11 13:25 UTC, Bybianca628 requested changes
corriga as duas equações que devem ficar em linhas próprias e o PR será aceito

2024-11-17 14:29 UTC, renatarmd commented
Substituí os arquivos homotopia-teorema-da-bola-cabeluda.tex e homotopia-identidade-e-antipoda.tex por novos, com as equações longas em linhas próprias

2024-11-26 00:09 UTC, renatarmd commented
Adicionei novos arquivos

2024-11-26 00:34 UTC, renatarmd commented
Corrigi alguns label que, quando compilei na minha máquina, percebi que geravam referências não eram clicáveis. Agora está funcionando.

2024-12-04 14:40 UTC, Bybianca628 commented on conteudo/grupo-fundamental-1-conexo-prop.tex
> +\begin{prop}[Nome da Afirmação]% ou af(afirmação)/prop(proposição)/corol(corolário)/lemma(lema)/outros ambientes devem ser definidos no preambulo de Alg.Top-Wiki.tex
Dar um nome para a proposição ou tirar o que está entre "[]"

2024-12-04 14:44 UTC, Bybianca628 commented on conteudo/grupo-fundamental-1-conexo-prop.tex
> +
apagar essa linha vazia

2024-12-04 14:45 UTC, Bybianca628 commented on conteudo/grupo-fundamental-1-conexo-prop.tex
> +    Se $\alpha \sim \beta ~(\text{rel }\partial I)$, então $\alpha(1)=\beta(1)$ pela definição de homotopia relativa, que mantém fixos os pontos de $\partial I$, em particular o $1$.
Eu acho que não tem necessidade de separar essas 5 sentenças em parágrafos diferentes. Talvez fique melhor tudo junto em um único parágrafo

2024-12-04 15:11 UTC, Bybianca628 commented on conteudo/grupo-fundamental-slsc-ex.tex
> +    Brinco Havaiano é a figura construída pela união de círculos $C_n$ que possuem centro $(\frac{1}{n}, 0)$ e raio $\frac{1}{n}$. Isto é, $\underset{n=1,~2,~3,...}{\bigcup} C_n$.
\underset{n\in\mathbb{N}}...

2024-12-04 15:19 UTC, Bybianca628 commented on conteudo/homotopia-identidade-e-antipoda.tex
> +	Se existe uma função contínua $v:S^n\rightarrow \mathbb{R}^{n+1}$ que leva todo $x\in S^n$ em $v(x)$ com $\langle x, v(x) \rangle =0$, isto é, um campo vetorial contínuo tangente à esfera, com $v(x)
v:S^n\rightarrow \mathbb{R}^{n+1}\backslash\{0\}... ,isto é, um campo vetorial não nulo contínuo e tangente à esfera, então as funções...

acho que assim fica melhor

2024-12-04 15:26 UTC, Bybianca628 reviewed
Feitas as correções o PR será aceito.

2024-12-15 20:18 UTC, renatarmd commented
Fiz as correções solicitadas

2024-12-17 00:46 UTC, renatarmd commented
Adicionei mais arquivos - provavelmente meus últimos

2024-12-17 01:08 UTC, renatarmd commented
Adicionei linhas em algumas listas de consequências que foram úteis nos resultados dos arquivos que acabei de postar.

2024-12-17 01:33 UTC, Bybianca628 commented on conteudo/espaco-de-recobrimento-recobrimento-1-conexo-lema.tex
> +Comentário sobre os objetos envolvidos na afirmação.
excluir essa linha

2024-12-17 01:40 UTC, Bybianca628 commented on conteudo/espaco-de-recobrimento-recobrimento-1-conexo-prop.tex
> +    Por outro lado, se $i_*:\pi_1(U,x)\rightarrow \pi_1(X,x)$ é trivial, vamos verificar que $U$ é uniformemente recoberto. Em particular, verifiquemos que $p^{-1}(U)=\underset{[\gamma]\in q^{-1}(X)}
Tente se parar equações matemáticas mto grandes em suas próprias linhas.

2024-12-17 01:56 UTC, Bybianca628 commented on conteudo/espaco-de-recobrimento-recobrimento-1-conexo-thm.tex
> +Comentário sobre os objetos envolvidos na afirmação.
excluir essa linha

2024-12-17 02:14 UTC, Bybianca628 reviewed
Fazer as mudanças pedidas. A adição de imagens foi muito boa!

2024-12-17 17:32 UTC, renatarmd commented
Realizei as mudanças solicitadas

2025-01-07 18:18 UTC, merged