Ações de Grupos e Recobrimentos
Top-Alg-Wiki/Top.Alg.Wiki pull request #17
Opened 2024-11-22 17:22 UTC by Fernando-Afonso-IME

Adiciona arquivos sobre ações propriamente descontínuas e recobrimentos.

2024-12-04 19:51 UTC, Bybianca628 reviewed
O documento não compilou. Lembre sempre de verificar se o documento está compilando antes de abrir um PR.

2024-12-07 01:05 UTC, Fernando-Afonso-IME commented
Corrige falha na compilação.

2024-12-12 19:38 UTC, Bybianca628 commented on conteudo/ações-de-grupos-propriamente-descontínuas-def.tex
> +\begin{alignat*}{1}
Parece ter algo de errado nesse ambiente

2024-12-13 07:20 UTC, Fernando-Afonso-IME commented
Corrigi erro na digitação.

2024-12-13 08:12 UTC, Fernando-Afonso-IME commented
Fiz algumas melhorias e correções nesses arquivos.

2025-01-07 22:22 UTC, Bybianca628 commented on conteudo/ações-de-grupos-e-recobrimentos-prop.tex
> +\begin{thm}[Ações propriamente descontínuas geram recobrimentos]% ou af(afirmação)/prop(proposição)/corol(corolário)/lemma(lema)/outros ambientes devem ser definidos no preambulo de Alg.Top-Wiki.tex
Corrigir o enunciado do teorema. Quem é \psi e p? Existem condições sobre elas?

2025-01-07 22:24 UTC, Bybianca628 commented on conteudo/ações-de-grupos-e-recobrimentos-prop.tex
> +    Note que \[p^{-1}(U) = \coprod_{g \in U} V_g \] onde $V_g \subset X $ são abertos e ainda:
g\in U não faz sentido se U\subset X/G

2025-01-07 22:27 UTC, Bybianca628 commented on conteudo/ações-de-grupos-e-recobrimentos-prop.tex
> +        \begin{cases}
o ambiente cases precisa estar dentro de um ambiente matemático. É melhor usar dois "$$$$".

2025-01-07 22:29 UTC, Bybianca628 commented on conteudo/ações-de-grupos-e-recobrimentos-prop.tex
> +    Dado $x \in X$, seja $V_1$ vizinhança de $x$ tal que $gV_1\cup V_1 \neq \emptyset \Rightarrow g = 1$\\
\cap no lugar de \cup

2025-01-07 22:32 UTC, Bybianca628 commented on conteudo/ações-de-grupos-e-gr-fundamental-prop.tex
O grp fundamental geralmente é denotado por pi minusculo.

2025-01-07 22:38 UTC, Bybianca628 commented on conteudo/ações-de-grupos-e-recobrimentos-ex.tex
O grupo fundamentla geralmente é denotado por pi minúsculo

2025-01-07 22:39 UTC, Bybianca628 commented on conteudo/ações-de-grupos-e-recobrimentos-ex.tex
> +             x\longmapsto x$ \ \ \ \ ação propriamente descontínua. Além disso,\\\\
n seria -x?

2025-01-07 22:41 UTC, Bybianca628 requested changes
Algumas alterações precisam ser feitas. Mas suas contribuições já serão consideradas para fins de nota

2025-01-08 18:19 UTC, Fernando-Afonso-IME commented
Fiz as alterações necessárias.

2025-01-09 18:46 UTC, merged