Grupo fundamental
Top-Alg-Wiki/Top.Alg.Wiki pull request #5
Opened 2024-09-06 19:50 UTC by Haoyu-Chen-math

Adicionei o conteúdo de grupo fundamental.

2024-09-16 19:20 UTC, Top-Alg-Wiki requested changes
O documento não está compilando, parece que exist alguma inconsistência no jeito em que os arquivos foram importados no documentos grupo-fundamental.tex. Verificar se os nomes estão certos

2024-09-17 00:22 UTC, Haoyu-Chen-math commented
Eu citei nome errado mesmo, arrumei agora

2024-09-17 00:23 UTC, Haoyu-Chen-math commented
vou submeter de novo

2024-09-19 16:47 UTC, Top-Alg-Wiki requested changes
a maioria dos comentários são mais sugestões para o aprimoramento do texto. Porém as homotopias que eu comentei que não estão definidas para t=1 fazem com que a demonstração não esteja correta. Corrigindo essa demonstração o PR será aceito

2024-09-19 16:47 UTC, Top-Alg-Wiki commented on conteudo/produto-bem-definido-gr-fundamental-prop.tex
> +    $$[\alpha]\cdot[\beta]=[\alpha*\beta]=[\alpha'*\beta]=[\alpha']\cdot [\beta']$$
[\alpha]\cdot[\beta]=[\alpha*\beta]=[\alpha'*\beta']=[\alpha']\cdot [\beta']

2024-09-19 16:47 UTC, Top-Alg-Wiki commented on conteudo/produto-bem-definido-gr-fundamental-prop.tex
> +O produto concatenação induz um produto $\cdot$ (operação binária) para o espaço quociente $\pi_1(X,x_0),$ além disso, $(\pi_1(X,x_0),\cdot)$ se forma um grupo.
se forma um grupo. -> forma um grupo.

2024-09-19 16:47 UTC, Top-Alg-Wiki commented on conteudo/produto-bem-definido-gr-fundamental-prop.tex
> +        H(s,t)=\begin{cases}
essa homotopia não está definida para t=1

2024-09-19 16:47 UTC, Top-Alg-Wiki commented on conteudo/produto-bem-definido-gr-fundamental-prop.tex
> +        G(s,t)=\begin{cases}
essa homotopia não está definida para t=1

2024-09-19 16:47 UTC, Top-Alg-Wiki commented on conteudo/homomorfismo-de-grupo-fundamental-prop.tex
> +        f_*([\alpha]\cdot [\beta]=f_*[\alpha*\beta]=[f\circ (\alpha*\beta)]=[(f\circ\alpha)*(f\circ\beta)]=(f_*[\alpha])\cdot (f_*[\beta])
f_*([\alpha]\cdot [\beta])=

2024-09-19 16:47 UTC, Top-Alg-Wiki commented on conteudo/homomorfismo-de-grupo-fundamental-prop.tex
> +Na consequência, temos que $\pi_1(X,x_0)$ é invariante topológico.
Como consequência

2024-09-19 16:47 UTC, Top-Alg-Wiki commented on conteudo/grupo-fundamental-def.tex
> +	\item \hyperref[produto-bem-definido-prop]{Dependência 1};\\ %'dependencia1' é o label onde o conceito Dependência 1 aparece (--à arrumar um padrão para referencias e labels--)
talvez trocar Dependência 1 para Produto de laços

2024-09-19 16:47 UTC, Top-Alg-Wiki commented on conteudo/grupo-fundamental-def.tex
> +	\item \hyperref[hom-grupo-fundamental]{Consequência 1};\\ %'consequencia1' é o label onde o conceito Consequência 1 aparece
talvez trocar Consequência 1 para homomorfismo induzido, ou algo do tipo

2024-09-19 16:47 UTC, Top-Alg-Wiki commented on conteudo/grupo-fundamental.tex
> +O grupo fundamental de um espaço topológico é o grupo das classes de equivalência sob homotopia dos laços contidos no espaço. Ele armazena certas informações sobre buracos do espaço topologico, e é i
quando quisermos
são homeomorfos (homotópicos)

2024-09-26 18:00 UTC, merged